name: terraform plan

run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  terraform-plan:
    concurrency:
      group: terraform-plan-and-apply
    runs-on: 'ubuntu-latest'
    if: (github.event_name != 'workflow_dispatch'
      || (github.event_name == 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')))
      && (github.ref != 'refs/heads/main' || (github.ref == 'refs/heads/main' && github.run_attempt == 1))
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: 419492
          private_key: ${{ secrets.APP_PRIVATEKEY }}

      - name: Checkout sensu terraform
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform Provider and Modules
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
            time: '30s'

      - name: Apply the terrraform plan generated
        run: terraform apply